project_id = "aywuwyqscrtavulqijxm"

[project]
project_id = "aywuwyqscrtavulqijxm"

[functions.daily-quote]
verify_jwt = false

[functions.sync-hubspot]
verify_jwt = true

[functions.import-quotes]
verify_jwt = true

[functions.send-daily-quotes]
verify_jwt = true

[functions.sync-resend-contacts]
verify_jwt = true

[functions.send-auth-email]
verify_jwt = false

[functions.broadcast-email]
verify_jwt = true
