project_id = "aywuwyqscrtavulqijxm"

[project]
project_id = "aywuwyqscrtavulqijxm"

[functions.daily-quote]
verify_jwt = false

[functions.sync-hubspot]
verify_jwt = true

[functions.import-quotes]
verify_jwt = false